### PR TITLE
Added a method in the controller to search by entry number

### PR DESCRIPTION
**Pull request by danielwilliams12**
Sorry, I didn't do this pull request correctly earlier today.

### CODE REVIEW

**Comment by chikamichi** [comment]
Nice work.

One behavior that is not covered by your current implementation is:

> Handle invalid input by prompting the user to enter a valid entry number.

I'd like you to review [that example](http://stackoverflow.com/questions/20387173/how-do-i-loop-a-request-for-user-input-until-the-user-enters-the-correct-info/20387383#20387383) and try to adapt your code to reuse the same idea.

**Comment by danielwilliams12** [comment]
Jean-Denis

As I’m on branch checkpoint-23, and the code is in checkpoint-22 I can’t see the code I created earlier. If I try to change I get a warning that I will lose my current changes. I need to stash the current branch, go back, make the changes, and then try to go back to the branch I’m working. So I will try to do this and let you know how it goes.

 

 

 

Dan Williams, PMP, CSP

Cell: 325-877-6333

**Comment by chikamichi** [comment]
Yes, that's the idea.

``` sh
# while on branch checkpoint-23-address_bloc-CSV
git stash
git checkout checkpoint-22-Addressbloc-menu-assignment
# do your changes…
git add .
git commit -m "Pick a message here"
git push
# resuming work on cp 23
git checkout checkpoint-23-address_bloc-CSV
git stash pop
```

**Comment by danielwilliams12** [comment]
Thanks for the insight Jean-Denis

I will try this out tomorrow and work on the code in Checkpoint - 22

 

 

 

Dan Williams, PMP, CSP

Cell: 325-877-6333

**Comment by danielwilliams12** [comment]
Jean-Denis

I could refactor the code to use a while loop or the version below the while example on with the same result on stackoverflow

http://stackoverflow.com/questions/20387173/how-do-i-loop-a-request-for-user-input-until-the-user-enters-the-correct-info/20387383#20387383              

user_input = 0

    until [1,2].include? user_input do

        puts "Please enter a 1 or a 2.>" 

        user_input = gets.chomp.to_i

    end

    if user_input == 1    

        puts "One response." 

    else   

        puts "Second response." 

    end

 

But…

The code I have does, I think, fulfill the requirement which is:

·         Handle invalid input by prompting the user to enter a valid entry number.

 

else

          system "clear"

          puts "Sorry, that is not a valid input"

          main_menu

        end

 

If the user enters an invalid number, they are returned to the menu and prompted to reenter the selection.

 

Correct?

 

Thanks

 

Dan Williams, PMP, CSP

Cell: 325-877-6333

**Comment by danielwilliams12** [comment]
Referring to my last email

I could refactor the code to this:

The code works either way

 

until [1,2,3,4,5,6].include? selection do

            system "clear"

            puts "Sorry, that is not a valid input"

            main_menu

        end

        if selection == 1

          system "clear"

          view_all_entries

          main_menu  

        elsif

          selection == 2

          system "clear"

          create_entry

          main_menu

…

 

Or I could use the case example to do the same thing

Which is preferred?

 

Thanks  

 

 

 

Dan Williams, PMP, CSP

Cell: 325-877-6333

**Comment by danielwilliams12** [comment]
Done

**Pull request closed without merging**
